### ISSUE TITLE
Timeout = 0 - still supported?

### ISSUE THREAD

**Issue by jayarjo** [browserstack/api#2]
<pre>
(timeout=30)

A number in seconds before the worker is terminated. Set this to 0 to keep the worker alive 
indefinitely.

IMPORTANT! If you have set the timeout to 0. Make sure you remember to terminate 
the worker otherwise it will continue to use up your credits. Irrespective of timeout 
parameter, a browser worker is alive for a maximum time of 1,800 seconds.
</pre>

Is a timeout of 0 still supported? Doesn't  feel like 1800 seconds in my tests, maybe 5-10 mins max.

**Comment by nakula** [comment]
This should be good now.
