### ISSUE TITLE
Any way to update job name?

### ISSUE THREAD

**Issue by arjunjh10** [browserstack/api#26]
Hello,
I am currently using the https://github.com/scottgonzalez/node-browserstack package to use browserstack's API,
I am using the api to update my job's status and name but somehow the name just wont update.
Is there a way to achieve that?

**Comment by AnkurGel** [comment]
Hi @arjunjh10 
We currently do not support updating name of session/build. With our REST API and it's client libraries, we only allow to change the status.

\- Ankur Goel
BrowserStack Automate

**Comment by arjunjh10** [comment]
Hey @AnkurGel I would be a great feature in my view. I have used SauceLabs before and their apis do allow to change the session name and other details. 
I have recently switched to Browserstack and suggested my company to buy the subscription :) 
Please please please... can this be a feature request.. It will be so awesome if it is

**Comment by arjunjh10** [comment]
Hi, just wondering if this feature request is likely to be on your product roadmap any time soon? Thanks

**Comment by francisf** [comment]
Hi @arjunjh10 , you can find details to update the session/build name via rest-api. You can find details [here](https://www.browserstack.com/automate/rest-api).
