### ISSUE TITLE
[Question] What is the maximum number of jobs we can queue before they run?

### ISSUE THREAD

**Issue by abdulhannanali** [browserstack/api#34]
Hello,

I wanted to ask, how many jobs can we queue before they run through the API? Are there any hard limits after which the response returned by API would be different? Looking forward for response. 

Thanks a lot.

Kind Regards,
Hannan

**Comment by abdulhannanali** [comment]
Meowww!

**Comment by swapnilagarwwal** [comment]
Hi @abdulhannanali, 

BrowserStack offers sufficiently large queues and does not impose any limit for queuing testing run through the API.

You should be able to run your tests without any trouble. Please reach out to us if you need any help.
Happy testing!

**Comment by abdulhannanali** [comment]
Thanks a lot for response!
