### ISSUE TITLE
Worker Ids are not being returned from the /workers call

### ISSUE THREAD

**Issue by tysoncadenhead** [browserstack/api#4]
There must have been a change made to the api recently, because the call to get all of the workers is no longer returning the worker id for each of the workers. Instead, I am just getting:

[{ browser: 'firefox',
    version: '15.0',
    os: 'win',
    status: 'running' },
  { browser: 'firefox',
    version: '15.0',
    os: 'win',
    status: 'queue' }]

What happened to the worker ids? They were in that array last week...

**Comment by rahulnwn** [comment]
This should be good now.
