### ISSUE TITLE
API for an SSO user

### ISSUE THREAD

**Issue by timrittgers** [browserstack/api#49]
Is it possible to formulate a url that can be hit in the browser to take a user with browserstack SSO credentials to a specific url in a specific browser? The use case would be to have GitHub actions build specific links for testing for our dev team.

**Comment by hritik-m** [comment]
Hi there,

Kindly directly raise a support ticket by sending us an email to [support@browserstack.com] or via Contact Us [here](https://www.browserstack.com/contact).

Thanks.
